
// *** Warning:
// *** auto-generated file and subjected to be overwritten

// path: ./app_models/transmission_line/autogenerated/model_observer.hpp

#pragma once

void Model::observer(
	const states_type 	&x ,
	const double 		&t,
	observer_type 		&ymat,
	const mids_type 	&last_observed_mids,
	const time_type 	&last_observed_t,
	inputs_type			&u
	)
{
	mids_type mid;
	intermediates(u,x,mid,t,last_observed_mids,last_observed_t);

	// y0	v_in;
	// y1	v_end;

	ymat(outputs::v_in)=mid(mid.index_v_in);
	ymat(outputs::v_end)=mid(mid.index_v_end);

}
